import type { Metadata } from "next";
import "./styles/style.css";
import Header from "./components/Header";
import Footer from "./components/Footer";
import AppcontextProvider from "./contexts/AppcontextProvider";
import Pagemessage from "./components/Pagemessage";
import { SessionProvider } from "next-auth/react";

// import { Inter } from "next/font/google";
// const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "policee",
  description: "Generated by policee",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <AppcontextProvider>
          {/* <SessionProvider> */}
            <Header />
            <Pagemessage />
            {children}
            <Footer />
          {/* </SessionProvider> */}
        </AppcontextProvider>
      </body>
    </html>
  );
}
