"use client";
import React, { useEffect, useState } from "react";
import Breadcrums from "./(components)/Breadcrums";

const Faq = () => {
  const [faq, setfaq] = useState<faqs>([]);
  useEffect(() => {
    setfaq([
      {
        heading:
          "What is Privacy Policy Summarization and how does your website help with it?",
        content:
          "Privacy Policy Summarization is the process of extracting the key points and important details from a privacy policy document and presenting them in a clear and concise format. Our website simplifies this process by allowing users to upload their privacy policy documents or provide links to them. Our advanced algorithms then analyze the text and generate easy-to-understand summaries, making it easier for users to comprehend their rights and obligations regarding their personal data.",
      },
      {
        heading: "Are the summaries provided by your website legally binding?",
        content:
          "No, the summaries generated by our website are for informational purposes only. While we strive for accuracy, the summaries may not capture every detail of the original document. It's important to note that the original privacy policy remains legally binding, and users should refer to it for complete understanding of their rights and responsibilities.",
      },
      {
        heading: "How accurate are the summaries generated by your platform?",
        content:
          "We employ state-of-the-art natural language processing algorithms to ensure the accuracy of our summaries. However, it's essential to understand that our summaries are generated automatically and may not always capture the nuances of the original document. We recommend reviewing the original privacy policy for comprehensive insight.",
      },
      {
        heading: "Is your platform free to use?",
        content:
          "Yes, our platform is completely free for users. We believe in promoting accessibility and transparency in privacy policies without any cost barriers.",
      },
      {
        heading: "How secure is my data when using your platform?",
        content:
          "We prioritize the security and privacy of our users' data. Any documents uploaded to our platform are processed securely, and we do not store or share them with third parties. Your data remains confidential throughout the summarization process.",
      },
      {
        heading:
          "What if I have feedback or encounter issues with your platform?",
        content:
          "We welcome feedback and are committed to providing the best possible experience for our users. If you have any suggestions, encounter issues, or need assistance, please don't hesitate to contact us through the feedback form on our website or by emailing us at contact@yourdomain.com. Our dedicated team is here to help resolve any concerns you may have.",
      },
    ]);
  }, []);

  return (
    <main id="faqpage">
      <div className="page">
        <h1 className="heading">Frequently Asked Questions</h1>
        <br />

        <p>
          Ever clicked &quot;accept&quot; on a privacy policy without truly
          understanding it? You&apos;re not alone. Privacy policies are often
          lengthy and complex, leaving us confused about our data. Our Privacy
          Policy Summarization tool cuts through the legalese to give you the
          key information you need in seconds. Simply enter a website&apos;s
          URL, and we&apos;ll provide a clear, concise breakdown of their data
          practices. Take back control of your online privacy – start exploring
          with our FAQs today!
        </p>

        {faq &&
          faq.map((item, index) => <Breadcrums item={item} key={index} />)}
      </div>
    </main>
  );
};

export default Faq;
